#$ -r y                      # Restartable
#$ -ckpt user                # Restart under user; do not change (do not replace with your username)
#$ -V                        # Inherit current environment
#$ -cwd                      # Start job in submission directory
#$ -N Diflunisal_LAM15           # Job Diflunisal
#$ -j y                      # Combine stderr and stdout
#$ -q MS,COE-GPU,UI-GPU               # Queue
#$ -l ngpus=1
#$ -l gpu_p100=false
#$ -pe smp 10              # Request 12 tasks/node, 12 total
#$ -o $JOB_NAME.$JOB_ID.log  # Diflunisal of output file
#$ -l h_rt=500:00:00         # Run Time
#$ -S /bin/bash              # Shell to use

module purge
source /Dedicated/schnieders/andthiel/miniconda.sh

/Dedicated/schnieders/andthiel/miniconda3/bin/python /Dedicated/schnieders/maemmad/binding_free_energy/Production.py --pdb_file /Dedicated/schnieders/maemmad/binding_free_energy/workflow/Diflunisal/Guest_Workflow/Diflunisal_solv_min.pdb  --forcefield_file /Dedicated/schnieders/maemmad/binding_free_energy/workflow/Diflunisal/Template/Guest/Diflunisal.xml /Dedicated/schnieders/maemmad/binding_free_energy/workflow/Diflunisal/Template/Guest/hp-bcd.xml --nonbonded_method "PME" --num_steps 15000000 --step_size 2 --nonbonded_cutoff 1.0 --vdw_lambda 0.725 --elec_lambda 0.0 --alchemical_atoms 1-26
